"""The golden corpus: loading it, generating it, and checking a run against it.

A golden label says what this stage SHOULD do with a form. Labels are anchored
to the sha256-pinned text snapshots, not to any run, so the corpus covers all 20
subjects while only two have ever been through a v3 run.

OCCURRENCE LABELS ARE COMPUTED, NOT OPINED. Where a form occurs is a fact, so
they are generated by the pipeline's own collector — which makes them an exact
oracle for the mechanical half, and means a disagreement is a real defect rather
than a difference of opinion. Their warrant is a verified sample, recorded on
each label's provenance; everything else in the corpus (snippet extent,
location, grouping, inheritance) is a judgment and needs a reader.

The generator deliberately calls `core.utils.aggregation_fold.collect_window` —
the production code — rather than a re-implementation. A re-implementation would
drift, and an oracle that drifts from the thing it measures is worse than none.
The check that keeps this honest is that the labels are anchored to QUOTES: if
the collector changes what it finds, the quote still says what the text holds,
and the diff is visible rather than silently absorbed.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional

import yaml

try:
    from . import loading, paths
except ImportError:  # pragma: no cover - script/package dual import
    import loading  # type: ignore[no-redef]
    import paths  # type: ignore[no-redef]

VALID_STATUSES = ("candidate", "confirmed", "disputed", "retired")
VALID_KINDS = ("occurrence", "snippet", "location", "grouping", "inheritance")
REQUIRED_LABEL_KEYS = frozenset({"id", "form", "kind", "status", "expect", "provenance"})

# Only `confirmed` labels gate. An unverified corpus gates nothing — the search
# harness fired a FALSE RED from an unverified expectation, and the rule it
# learned applies here unchanged.
GATING_STATUS = "confirmed"


@dataclass(frozen=True)
class GoldenLabel:
    id: str
    form: str
    kind: str
    status: str
    expect: dict[str, Any]
    evidence: tuple[dict[str, Any], ...]
    notes: str
    subject: str
    field: str

    @property
    def gates(self) -> bool:
        return self.status == GATING_STATUS

    @property
    def must_not_occur(self) -> bool:
        return bool(self.expect.get("must_not_occur")) or (
            self.expect.get("occurrences") == 0
        )


def _label(raw: dict[str, Any], subject: str, field: str) -> GoldenLabel:
    return GoldenLabel(
        id=str(raw.get("id", "")),
        form=str(raw.get("form", "")),
        kind=str(raw.get("kind", "")),
        status=str(raw.get("status", "")),
        expect=raw.get("expect") or {},
        evidence=tuple(raw.get("evidence") or ()),
        notes=str(raw.get("notes", "") or ""),
        subject=subject,
        field=field,
    )


def load_field_goldens(path: Path) -> tuple[dict[str, Any], list[GoldenLabel]]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    subject = str(payload.get("subject", ""))
    field = str(payload.get("field", ""))
    labels = [_label(raw, subject, field) for raw in (payload.get("labels") or [])]
    return payload, labels


def load_subject_goldens(subject: str) -> dict[str, list[GoldenLabel]]:
    """Every field's labels for one subject, keyed by field."""
    out: dict[str, list[GoldenLabel]] = {}
    directory = paths.goldens_dir(subject)
    if not directory.is_dir():
        return out
    for field in paths.PHRASE_FIELDS:
        path = directory / f"{field}.yaml"
        if path.is_file():
            _, labels = load_field_goldens(path)
            out[field] = labels
    return out


def validate_label(raw: dict[str, Any]) -> list[str]:
    """Schema problems in one label, as human-readable strings."""
    problems: list[str] = []
    missing = REQUIRED_LABEL_KEYS - set(raw)
    if missing:
        problems.append(f"missing keys: {sorted(missing)}")
    if raw.get("status") not in VALID_STATUSES:
        problems.append(f"status {raw.get('status')!r} not in {VALID_STATUSES}")
    if raw.get("kind") not in VALID_KINDS:
        problems.append(f"kind {raw.get('kind')!r} not in {VALID_KINDS}")
    provenance = raw.get("provenance")
    if not isinstance(provenance, list) or not provenance:
        problems.append("provenance must be a non-empty list")
    expect = raw.get("expect")
    if not isinstance(expect, dict) or not expect:
        problems.append("expect must be a non-empty mapping")
    # A confirmed label must carry its warrant: a second pass, recorded.
    if raw.get("status") == GATING_STATUS and isinstance(provenance, list):
        actions = {str(row.get("action")) for row in provenance if isinstance(row, dict)}
        if "verified" not in actions:
            problems.append(
                "confirmed labels need a 'verified' provenance row (second pass)"
            )
    return problems


# ---------------------------------------------------------------------------
# generation


def _collector():
    """The production collector, imported lazily.

    Imported here rather than at module scope so the rest of the harness — and
    its tests — never pay for the pipeline packages.
    """
    core_src = paths.REPO_ROOT / "packages" / "core" / "src"
    if str(core_src) not in sys.path:
        sys.path.insert(0, str(core_src))
    from core.utils.aggregation_fold import collect_window  # noqa: PLC0415

    return collect_window


def generate_occurrence_labels(
    subject: str,
    field: str,
    forms: Iterable[str],
    *,
    text: Optional[str] = None,
    id_prefix: Optional[str] = None,
    limit_chars: Optional[int] = None,
) -> list[dict[str, Any]]:
    """One `occurrence` label per form, computed from the pinned snapshot.

    Every label — including the zero-occurrence ones — is emitted: a form the
    text does not contain is as much a fact about this stage as one it contains
    fourteen times, and the negative half is where the substring traps live
    (`PET` inside "competitive", `ITAR` inside "Military").

    Labels come out as `candidate`. Promotion to `confirmed` needs a reader's
    second pass, per GOLDEN_LABELS_SCHEMA.md.
    """
    body = text if text is not None else loading.load_text(subject)
    if body is None:
        raise FileNotFoundError(f"no pinned snapshot for {subject}")
    if limit_chars:
        body = body[:limit_chars]

    collect_window = _collector()
    forms = sorted({f for f in forms if f and f.strip()})
    collection = collect_window(body, forms)

    by_form: dict[str, list[Any]] = {form: [] for form in forms}
    for mention in collection.mentions:
        by_form.setdefault(mention.sent_form or mention.form, []).append(mention)

    slug = paths.subject_slug(subject)
    prefix = id_prefix or f"{slug}-{field}"
    labels: list[dict[str, Any]] = []
    for index, form in enumerate(forms, start=1):
        found = by_form.get(form) or []
        expect: dict[str, Any] = {"occurrences": len(found)}
        if not found:
            expect["must_not_occur"] = True
            # The gap between a whole-word count of zero and a naive substring
            # count is exactly the trap a careless matcher falls into, so record
            # it on the label rather than leaving it to be rediscovered.
            naive = body.lower().count(form.lower())
            if naive:
                expect["naive_substring_hits"] = naive
        evidence = [
            {
                "quote": m.snippet.strip()[:300],
                "approx_offset": m.start,
            }
            for m in found[:3]
        ]
        pages = sorted({m.page for m in found if m.page})
        if pages:
            expect["pages"] = pages[:5]
        labels.append(
            {
                "id": f"{prefix}-{index:04d}",
                "form": form,
                "kind": "occurrence",
                "status": "candidate",
                "expect": expect,
                "evidence": evidence,
                "notes": "",
                "provenance": [
                    {
                        "action": "added",
                        "by": "occurrence-generator",
                        "date": "2026-08-27",
                        "source": "computed:collect_window",
                    }
                ],
            }
        )
    return labels


# ---------------------------------------------------------------------------
# checking a run


@dataclass
class GoldenFinding:
    label_id: str
    form: str
    kind: str
    detail: str
    expected: Any
    actual: Any
    # A gating finding is a defect this stage owns outright. A non-gating one is
    # a DIFFERENCE: run and corpus disagree, both an innocent and a guilty
    # reading exist, and only a reader can say which. Non-gating never means
    # ignorable — it means "reported for examination, not counted as a RED".
    gating: bool = True

    def as_dict(self) -> dict[str, Any]:
        return {
            "label_id": self.label_id,
            "form": self.form,
            "kind": self.kind,
            "detail": self.detail,
            "expected": self.expected,
            "actual": self.actual,
            "gating": self.gating,
        }


def check_occurrences(
    run: loading.FieldRun, labels: Iterable[GoldenLabel]
) -> tuple[list[GoldenFinding], dict[str, Any]]:
    """Compare a run's mentions against the occurrence labels that gate.

    Two deliberate leniencies, both from GOLDEN_LABELS_SCHEMA.md:

    * A label is only checked when its form was actually SENT in this run.
      Whether search sent it is the search eval's question; charging this stage
      for a form it never received would import that eval's failures.
    * Counts are compared per subject, not per window. The pipeline reads a
      page-trimmed copy with a 2-chunk cap, so a golden count taken over the
      full text is an upper bound; only a MUST-NOT-OCCUR violation is exact.

    NEITHER LENIENCY MAY SWALLOW A DISAGREEMENT. Standing user rule
    (2026-08-28): where the run and the eval set differ, the difference is
    examined, never agreed in passing — and examining it starts with the
    instrument SAYING it happened. Both leniencies used to hide one:

    * "not sent" conflated a form search never sent with a form search DID send
      and this stage then found nothing for. The first is genuinely out of
      scope; the second is either under-collection here or a wrong golden count.
      The fold's windows record `zero_hit_forms`, so the two are separable.
    * an UNDER-count was not reported at all — only over-counts were. The
      trimmed copy explains an under-count; it does not excuse hiding it.

    Both recovered cases are reported as NON-GATING differences. They have a
    legitimate innocent explanation, so they must not fire a RED; they are also
    exactly the rows a reader has to adjudicate, so they must not be silent.
    """
    found_by_form: dict[str, int] = {}
    for mention in run.mentions():
        key = mention.sent_form or mention.form
        found_by_form[key] = found_by_form.get(key, 0) + 1

    # Forms search handed to at least one window that scored no hit in it. A
    # form can be zero-hit in one window and found in another, so this is
    # evidence of "was sent" only — never of "is absent". Absence is decided by
    # found_by_form, over the whole subject.
    sent_zero_hit: set[str] = set()
    for window in run.windows:
        sent_zero_hit.update(window.zero_hit_forms)

    findings: list[GoldenFinding] = []
    checked = not_sent = 0
    for label in labels:
        if label.kind != "occurrence" or not label.gates:
            continue
        actual = found_by_form.get(label.form, 0)
        if label.must_not_occur:
            # Exact: the form is not in the text at all, so ANY mention of it is
            # a boundary or matching defect in this stage.
            checked += 1
            if actual:
                findings.append(
                    GoldenFinding(
                        label.id, label.form, label.kind,
                        "form absent from the snapshot was nevertheless collected "
                        "(substring or word-boundary defect)",
                        0, actual,
                    )
                )
            continue

        expected = label.expect.get("occurrences")
        if label.form not in found_by_form:
            if label.form in sent_zero_hit:
                checked += 1
                findings.append(
                    GoldenFinding(
                        label.id, label.form, label.kind,
                        "sent to the scan and collected zero times, while the "
                        "corpus records occurrences in the pinned text — "
                        "under-collection here, occurrences that fell outside "
                        "the trimmed copy, or a wrong golden count",
                        expected, 0, gating=False,
                    )
                )
            else:
                # Nothing in this run's record says the form was ever handed to
                # the scan. Out of scope: that is the search eval's question.
                not_sent += 1
            continue

        checked += 1
        if not isinstance(expected, int):
            continue
        if actual > expected:
            findings.append(
                GoldenFinding(
                    label.id, label.form, label.kind,
                    "more occurrences than the full-text golden count — the "
                    "trimmed text cannot hold more than the whole text",
                    expected, actual,
                )
            )
        elif actual < expected:
            findings.append(
                GoldenFinding(
                    label.id, label.form, label.kind,
                    "fewer occurrences than the full-text golden count — "
                    "expected wherever the trim dropped pages, a collection "
                    "defect otherwise",
                    expected, actual, gating=False,
                )
            )

    gating_count = sum(1 for f in findings if f.gating)
    return findings, {
        "occurrence_labels_checked": checked,
        "occurrence_labels_not_sent": not_sent,
        # Renamed meaning 2026-08-28: `occurrence_findings` is now the GATING
        # count alone, with the examine-me rows counted separately. No trend row
        # is affected — no label has ever gated, so both were 0 everywhere.
        "occurrence_findings": gating_count,
        "occurrence_differences": len(findings) - gating_count,
    }
