"""Environment variables required by `data_etl_app`, grouped by concern."""

APP_HOSTING = ["PROTOCOL", "HOSTED_AT", "PORT"]

GOOGLE_MAPS = ["GOOGLE_MAPS_API_KEY"]

ONTOLOGY_URIS = [
    "SUDOKN_PROCESS_CAP_BASE_URI",
    "SUDOKN_MATERIAL_CAP_BASE_URI",
    "SUDOKN_INDUSTRY_BASE_URI",
    "SUDOKN_CERTIFICATE_BASE_URI",
    "SUDOKN_OWNERSHIP_STATUS_BASE_URI",
    "SUDOKN_NAICS_BASE_URI",
]
