#!/bin/bash
# Clears stuck failed Prisma migrations generated by litellm_proxy_extras sanity check.
#
# When litellm_proxy_extras starts, it diffs the current schema.prisma against the live DB
# and writes a new migration file. If that migration tries to drop a column that a DB view
# depends on (e.g. LiteLLM_VerificationTokenView.access_group_ids), Postgres rejects it
# with error 2BP01. The migration is recorded as failed in _prisma_migrations, which blocks
# all future deploys until it is resolved.
#
# This typically recurs after branch switches when the litellm version changes.
#
# Usage:
#   ./reset_prisma_migrations.sh
#   ./reset_prisma_migrations.sh --dry-run   # print SQL without executing

set -e

PROJ_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
export PATH="$PROJ_ROOT/.venv/bin:$PATH"

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

# Read DATABASE_URL from environment or .env file
if [[ -z "${DATABASE_URL:-}" ]]; then
    ENV_FILE="$PROJ_ROOT/.env"
    if [[ -f "$ENV_FILE" ]]; then
        DATABASE_URL=$(grep -E '^DATABASE_URL=' "$ENV_FILE" | head -1 | cut -d= -f2-)
    fi
fi

if [[ -z "${DATABASE_URL:-}" ]]; then
    # Fall back to the default from docker-compose
    DATABASE_URL="postgresql://litellm:litellm@localhost:5432/litellm"
    echo "Warning: DATABASE_URL not set, using default: $DATABASE_URL"
fi

# Find all failed migrations in _prisma_migrations
echo "Checking for failed Prisma migrations..."

PSQL_CMD="$PROJ_ROOT/.venv/bin/python -c \"
import subprocess, sys
result = subprocess.run(
    ['psql', '${DATABASE_URL}', '-t', '-A', '-c',
     \\\"SELECT migration_name FROM \\\\\\\"_prisma_migrations\\\\\\\" WHERE rolled_back_at IS NULL AND finished_at IS NULL AND started_at IS NOT NULL;\\\"],
    capture_output=True, text=True
)
print(result.stdout.strip())
if result.returncode != 0:
    print(result.stderr, file=sys.stderr)
    sys.exit(result.returncode)
\""

# Use psql directly
FAILED=$(psql "${DATABASE_URL}" -t -A -c \
    "SELECT migration_name FROM \"_prisma_migrations\" WHERE rolled_back_at IS NULL AND finished_at IS NULL AND started_at IS NOT NULL;" \
    2>/dev/null || echo "")

if [[ -z "$FAILED" ]]; then
    echo "No failed migrations found."
else
    echo "Found failed migrations:"
    echo "$FAILED"
fi

# Build SQL
SQL=""

# 1. Drop the view that commonly blocks column drops
SQL+=$'\n'"DROP VIEW IF EXISTS \"LiteLLM_VerificationTokenView\" CASCADE;"

# 2. Mark all failed migrations as rolled back
while IFS= read -r migration; do
    [[ -z "$migration" ]] && continue
    SQL+=$'\n'"DELETE FROM \"_prisma_migrations\" WHERE migration_name = '${migration}';"
done <<< "$FAILED"

# 3. Delete any auto-generated diff migration files from litellm_proxy_extras
EXTRAS_MIGRATIONS="$PROJ_ROOT/.venv/lib/python3.12/site-packages/litellm_proxy_extras/migrations"

echo ""
echo "SQL to execute:"
echo "$SQL"
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[DRY RUN] Skipping execution."
else
    psql "${DATABASE_URL}" -c "$SQL"
    echo "Database reset complete."

    # Remove auto-generated diff migration directories (keep only the litellm-shipped ones)
    if [[ -d "$EXTRAS_MIGRATIONS" ]]; then
        echo "Cleaning up auto-generated migration diffs in litellm_proxy_extras..."
        # Auto-generated diffs have timestamps after the last shipped migration (20251115...)
        find "$EXTRAS_MIGRATIONS" -maxdepth 1 -type d -name "2026*" -exec rm -rf {} + 2>/dev/null || true
        echo "Done."
    fi
fi

echo ""
echo "Next step: pm2 restart <id> --update-env"
